export default {
    dsa: [
        // "depthFirstSearchOnBinarySearchTree",
        // "LeastRecentlyUsedCacheDS",
        // "LinearSearchList",
        "BinarySearchList",
        "TwoCrystalBalls",
        "BubbleSort",
        "InsertionSort",
        "MergeSort",
        "SinglyLinkedList",
        "DoublyLinkedList",
        "Queue",
        "Stack",
        // "ArrayList",
        // "MazeSolver",
        "QuickSort",
        // "BTPreOrder",
        // "BTInOrder",
        // "BTPostOrder",
        // "BTBFS",
        // "CompareBinaryTrees",
        // "depthFirstSearchOnBinarySearchTree",
        // "DFSGraphList",
        // "Trie",
        // "BFSGraphMatrix",
        // "Map",
        // "MinHeap",
    ],
};
